name: deploy-to-ec2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy files to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Setup and start Node.js app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Actualizar sistema
            sudo apt-get update -y

            # Instalar Node.js y PM2 si no están instalados
            curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
            sudo apt-get install -y nodejs
            sudo npm install -g pm2

            # Instalar dependencias de la app
            cd ${{ secrets.TARGET_DIR }}
            npm install

            # Reiniciar la aplicación con PM2
            pm2 stop all || true
            pm2 start index.js --name repositorio-perfiles --interpreter `which node`
            pm2 save
            pm2 startup systemd

            # Instalar y configurar Nginx
            sudo apt-get install -y nginx
            sudo rm -f /etc/nginx/sites-enabled/default
            echo 'server {
              listen 80;
              server_name _;
              location / {
                proxy_pass http://localhost:5000;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
                proxy_cache_bypass $http_upgrade;
              }
            }' | sudo tee /etc/nginx/sites-available/my-app

            # Activar la configuración y reiniciar Nginx
            sudo ln -s /etc/nginx/sites-available/my-app /etc/nginx/sites-enabled/
            sudo systemctl restart nginx
            sudo systemctl enable nginx
